### ISSUE TITLE
Chem++ Logo not showing up when running `Chem++ Windows.exe`

### ISSUE THREAD

**Issue by SlipperyDuck777** [chemplusplus/Chemplusplus#10]
# Describe the bug
When running `Chem++ Windows.exe` made by @WayneSeng the logo of Chem++ does not show up anywhere.

# To Reproduce

1. Run `Chem++ Windows.exe`
2. Try to find a logo anywhere

**Expected behavior**
The logo should be present

# Screenshots

1. https://i.imgur.com/IxfRWjc.png
2. https://i.imgur.com/uljMoIY.png
3. https://i.imgur.com/1VSUBup.png
4. https://i.imgur.com/1wCTvKh.png
5. https://i.imgur.com/K8GxxgL.png

# Desktop (please complete the following information):
 - OS: [Windows 10 Home, Version 21H1, Installed On: 2021-‎05-‎28, OS Build 19043.1165, Windows Feature Experience Pack 120.2212.3530.0]
 - Browser [Firefox Developer Edition]
 - Version [92.0b6 (64-bit)]
 - Update Channel [Aurora]

**Comment by WayneSeng** [comment]
Fixed in latest pr.

**Comment by SlipperyDuck777** [comment]
ok
