### ISSUE TITLE
Footer at the center will looks better

### ISSUE THREAD

**Issue by shreyshreyansh** [chemplusplus/Chemplusplus#3]
Before

![Screenshot 2021-08-08 112705](https://user-images.githubusercontent.com/53744971/128622392-c03a4cbe-fc52-496b-97dc-78b9b2f6bd19.png)

After (I think)

![Screenshot 2021-08-08 112823](https://user-images.githubusercontent.com/53744971/128622416-38c6a15e-abcd-40e3-8d93-423cb10da63e.png)

**Comment by MakusFrig** [comment]
Thanks for the heads up, you are right, it does look beetter the commit has gone through
