### ISSUE TITLE
Get Compound Struct

### ISSUE THREAD

**Issue by Gatorific888** [chemplusplus/Chemplusplus#5]
**Describe the bug**

After using the get struct function on the bot once to get the structure of a compound, after closing the drawing, trying to use the same mechanism returns a blank canvas and an error message. Only fixed via a relaunch.

**To Reproduce**
1. Type in water in get struct
2. Click on enter
3. The drawing works, then close the drawing
4. Rerun the program
5. See blank canvas and error message

**Expected behavior**

I expected to get another image of the compound that I typed in after closing the drawing of the previous one.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MakusFrig** [comment]
Thank you for reporting the issue this should be a simple fix and i will have it up and running within the hour

**Comment by MakusFrig** [comment]
Alright it has been fixed at least on my local machine I will make the commit and the new release right now, what was happening was there was no catch for if a compound name was not found in the pubchem database so it would not retrieve and image. Now it makes sure the retrieve the image before displaying the new window other wise it creates a new error window
